In [1]:
#logistic regression
import pandas as pd
d=pd.read_csv("heart_disease.csv")

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
d

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [4]:
d.isnull().sum()

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [5]:
d=d.dropna()

In [6]:
d.isna().sum()

Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Exercise Habits         0
Smoking                 0
Family Heart Disease    0
Diabetes                0
BMI                     0
High Blood Pressure     0
Low HDL Cholesterol     0
High LDL Cholesterol    0
Alcohol Consumption     0
Stress Level            0
Sleep Hours             0
Sugar Consumption       0
Triglyceride Level      0
Fasting Blood Sugar     0
CRP Level               0
Homocysteine Level      0
Heart Disease Status    0
dtype: int64

In [7]:
d

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
5,25.0,Male,152.0,257.0,Low,Yes,No,No,28.144681,No,...,No,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,68.0,Female,169.0,291.0,Medium,Yes,No,No,22.839718,No,...,No,Medium,Low,6.057509,High,299.0,142.0,3.321020,11.910244,Yes
9994,73.0,Female,144.0,191.0,Medium,Yes,Yes,Yes,39.459620,No,...,No,Medium,Low,7.549114,Medium,200.0,88.0,1.154904,8.021732,Yes
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [8]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7067 entries, 1 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   7067 non-null   float64
 1   Gender                7067 non-null   object
 2   Blood Pressure        7067 non-null   float64
 3   Cholesterol Level     7067 non-null   float64
 4   Exercise Habits       7067 non-null   object
 5   Smoking               7067 non-null   object
 6   Family Heart Disease  7067 non-null   object
 7   Diabetes              7067 non-null   object
 8   BMI                   7067 non-null   float64
 9   High Blood Pressure   7067 non-null   object
 10  Low HDL Cholesterol   7067 non-null   object
 11  High LDL Cholesterol  7067 non-null   object
 12  Alcohol Consumption   7067 non-null   object
 13  Stress Level          7067 non-null   object
 14  Sleep Hours           7067 non-null   float64
 15  Sugar Consumption     7067 non-null   object
 16  Triglyceride Level    7067 non-null   float64
 17  Fasting Blood Sugar   7067 non-null   float64
 18  CRP Level             7067 non-null   float64
 19  Homocysteine Level    7067 non-null   float64
 20  Heart Disease Status  7067 non-null   object
dtypes: float64(9), object(12)
memory usage: 1.2+ MB

In [9]:
cols = ['Smoking','Family Heart Disease','Diabetes','High Blood Pressure','Heart Disease Status','High LDL Cholesterol','Low HDL Cholesterol']
d[cols] = d[cols].replace({'Yes': 1, 'No': 0})

In [10]:
cols1=['Gender']
d[cols1]=d[cols1].replace({'Male': 1, 'Female': 0})

In [11]:
cols2=['Alcohol Consumption','Stress Level','Sugar Consumption','Exercise Habits']
d[cols2]=d[cols2].replace({'High':2,'Medium':1,'Low':0})

In [12]:
d.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,0,146.0,286.0,2,0,1,1,25.221799,0,...,0,1,2,8.744034,1,133.0,157.0,9.355389,19.298875,0
2,46.0,1,126.0,216.0,0,0,0,0,29.855447,0,...,1,0,0,4.440440,0,393.0,92.0,12.709873,11.230926,0
3,32.0,0,122.0,293.0,2,1,1,0,24.130477,1,...,1,0,2,5.249405,2,293.0,94.0,12.509046,5.961958,0
4,60.0,1,166.0,242.0,0,1,1,1,20.486289,1,...,0,0,2,7.030971,2,263.0,154.0,10.381259,8.153887,0
5,25.0,1,152.0,257.0,0,1,0,0,28.144681,0,...,0,0,1,5.504876,0,126.0,91.0,4.297575,10.815983,0

In [13]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7067 entries, 1 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   7067 non-null   float64
 1   Gender                7067 non-null   int64
 2   Blood Pressure        7067 non-null   float64
 3   Cholesterol Level     7067 non-null   float64
 4   Exercise Habits       7067 non-null   int64
 5   Smoking               7067 non-null   int64
 6   Family Heart Disease  7067 non-null   int64
 7   Diabetes              7067 non-null   int64
 8   BMI                   7067 non-null   float64
 9   High Blood Pressure   7067 non-null   int64
 10  Low HDL Cholesterol   7067 non-null   int64
 11  High LDL Cholesterol  7067 non-null   int64
 12  Alcohol Consumption   7067 non-null   int64
 13  Stress Level          7067 non-null   int64
 14  Sleep Hours           7067 non-null   float64
 15  Sugar Consumption     7067 non-null   int64
 16  Triglyceride Level    7067 non-null   float64
 17  Fasting Blood Sugar   7067 non-null   float64
 18  CRP Level             7067 non-null   float64
 19  Homocysteine Level    7067 non-null   float64
 20  Heart Disease Status  7067 non-null   int64
dtypes: float64(9), int64(12)
memory usage: 1.2 MB

In [15]:
import numpy as np

In [18]:
# Features
x = d[['Age','Gender','Blood Pressure','Cholesterol Level','Exercise Habits',
       'Smoking','Family Heart Disease','Diabetes','BMI','High Blood Pressure',
       'Low HDL Cholesterol','High LDL Cholesterol','Alcohol Consumption',
       'Stress Level','Sleep Hours','Sugar Consumption','Triglyceride Level',
       'Fasting Blood Sugar','CRP Level']]

# Target
y = d['Heart Disease Status']

# Convert to numpy if needed (optional, sklearn works with pandas DataFrames too)
x = np.array(X)   # shape: (n_samples, n_features)
y = np.array(y)   # shape: (n_samples,)

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [22]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [23]:
y_pred=lr.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [31]:
from sklearn.metrics import accuracy_score
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7901933050447902